[build-system]
requires = ["robotpy-build"]

[tool.robotpy-build]
base_package = "wpiutil"

[tool.robotpy-build.wrappers."wpiutil._impl"]

name = "wpiutil"
artname = "wpiutil-cpp"
baseurl = "https://frcmaven.wpi.edu/artifactory/release/edu/wpi/first/wpiutil"
version = "2020.1.1"

sources = []
extra_headers = [
    "wpiutil/include"
]

[tool.robotpy-build.metadata]
name = "robotpy-wpiutil"
description = "Binary wrapper for FRC WPIUtil library"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/robotpy-wpiutil"
license = "BSD-3-Clause"
install_requires = []
