[build-system]
requires = ["robotpy-build"]

[tool.robotpy-build]
base-package = "wpiutil"

[tool.robotpy-build.wrappers."wpiutil._impl"]

libname = "wpiutil"
artname = "wpiutil-cpp"
baseurl = "http://first.wpi.edu/FRC/roborio/maven/release/edu/wpi/first/wpiutil"
version = "2019.4.1"

sources = []
extra_headers = [
    "wpiutil/include"
]

[tool.robotpy-build.metadata]
name = "robotpy-wpiutil"
description = "Binary wrapper for FRC WPIUtil library"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/robotpy-wpiutil"
license = "BSD-3-Clause"
